title: Stylelint Sustainable CSS
description: Sustainable CSS is a Stylelint plugin dedicated to following sustainable web design principles.
theme: jekyll-theme-cayman # Choose any of the available themes