title: Stylelint Sustainable CSS
description: Sustainable CSS is a Stylelint plugin dedicated to following sustainable web design principles.
theme: ultra-minimal-theme # Choose any of the available themes